# Generated by Django 4.0.2 on 2022-02-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
