# Generated by Django 4.0.2 on 2022-02-04 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0004_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='superuser_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='superuser_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='access',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
