# Generated by Django 4.0.2 on 2022-02-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0005_server_superuser_name_server_superuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
