# Generated by Django 4.0.2 on 2022-02-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0006_server_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='superuser_password',
            field=models.CharField(max_length=512),
        ),
    ]
