# Generated by Django 4.0.2 on 2022-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='media/avatars/'),
        ),
    ]
