# Generated by Django 4.0.2 on 2022-02-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='Ansible_Infra/Ansible_Infra_App/static/media/avatars/None/'),
        ),
    ]
