# Generated by Django 4.0.2 on 2022-02-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Ansible_Infra_App', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='user',
        ),
        migrations.AddField(
            model_name='access',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
