# Generated by Django 4.0.2 on 2022-02-09 20:22

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0012_remove_access_user_access_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 2, 9, 20, 22, 45, 530318, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
