# Generated by Django 4.0.2 on 2022-02-12 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0013_access_description_access_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.CharField(max_length=150)),
                ('config', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ansible_Infra_App.server')),
            ],
        ),
    ]
