# Generated by Django 4.0.2 on 2022-02-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0016_setup_execplay_rem_dir_setup_play_rem_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='execplay_rem_dir',
            new_name='exec_play_rem_dir',
        ),
    ]
