# Generated by Django 4.0.2 on 2022-02-14 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0018_playbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='file',
            field=models.FileField(default=datetime.datetime(2022, 2, 14, 21, 48, 39, 607538, tzinfo=utc), upload_to='C:/Users/midou/OneDrive/Bureau/Projet/Ansible_Infra/Ansible_Infra_App/files/playbooks'),
            preserve_default=False,
        ),
    ]
