# Generated by Django 4.0.2 on 2022-02-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ansible_Infra_App', '0019_playbook_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playbook',
        ),
    ]
